services:
  web:
    build: .
    image: techruby-web:latest
    container_name: techruby-web
    restart: unless-stopped
    networks:
      - salamruby_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.techruby.rule=Host(`techruby.ir`)"
      - "traefik.http.routers.techruby.entrypoints=websecure"
      - "traefik.http.routers.techruby.tls=true"
      - "traefik.http.routers.techruby.tls.certresolver=default"
      - "traefik.http.services.techruby.loadbalancer.server.port=3000"

networks:
  salamruby_default:
    external: true
